### ISSUE TITLE
Error message when not using ?lang=

### ISSUE THREAD

**Issue by oehnstro** [Teknologforeningen/www.teknologforeningen.fi#17]
`Notice: Undefined index: lang in /app/index.php on line 53` when accessing page without `?lang=xx`

<img width="512" alt="screenshot 2015-12-21 18 20 14" src="https://cloud.githubusercontent.com/assets/917061/11935304/d1fed2c2-a80f-11e5-8081-f009dfae1a4c.png">

**Comment by thesauri** [comment]
Woops, should be fixed now.

**Comment by oehnstro** [comment]
Confirmed fixed with 14b1b18
