### ISSUE TITLE
Menu and language selector overlaps on phone in landscape

### ISSUE THREAD

**Issue by oehnstro** [Teknologforeningen/www.teknologforeningen.fi#20]
When viewing the site in landscape mode on iPhone the menu box and language selector texts overlap.
<img width="543" alt="screenshot 2015-12-28 20 01 17" src="https://cloud.githubusercontent.com/assets/917061/12023033/243d8702-ad9e-11e5-9425-160dfbedea64.png">

**Comment by thesauri** [comment]
Fixed in the latest pull request, #19.
