### ISSUE TITLE
Menu and language selector overlaps on windows 10 chrome, edge and posssible more

### ISSUE THREAD

**Issue by forssis** [Teknologforeningen/www.teknologforeningen.fi#23]
when viewing the site on chrome and edge the menu and language selector overlaps.
![hemsidan](https://cloud.githubusercontent.com/assets/16514922/12073745/18f12dee-b137-11e5-88dd-a9624c22ebb9.jpg)

**Comment by forssis** [comment]
it does this on smaller screens or smaller windows

**Comment by thesauri** [comment]
Thanks, should be fixed in my latest pull request. If not, let me know.

**Comment by walliski** [comment]
#24 I suppose.

**Comment by VonLatvala** [comment]
Pull request merged to master. Good job.
